# Generated by Django 4.2.5 on 2023-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('password1', models.CharField(max_length=225)),
            ],
        ),
    ]
