# Generated by Django 4.2.5 on 2023-11-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationModel',
        ),
    ]
