# Generated by Django 4.2.5 on 2024-04-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='avatar',
            field=models.ImageField(default='media/base/user_avatar.jpeg', upload_to='accounts/avatars/'),
        ),
    ]
