# Generated by Django 4.2.5 on 2024-04-15 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_blogmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagemodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.blogmodel'),
        ),
        migrations.AlterField(
            model_name='blogimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
