# Generated by Django 4.2.5 on 2024-04-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blogimagemodel_blog_alter_blogimagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimagemodel',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
