# Generated by Django 4.2.5 on 2024-04-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blogimagemodel_is_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimagemodel',
            name='is_thumbnail',
        ),
        migrations.AddField(
            model_name='blogimagemodel',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.blogimagemodel'),
        ),
    ]
