# Generated by Django 4.2.5 on 2024-03-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_alter_postmodel_image_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
